In [1]:
import numpy as np

# Array Arithmetic

## Scalar Arithmetic

In scalar arithmetic if any arithmetic operation is done on the array with a scalar value, the arithmetic operation will be done on each of the element of the array

In [4]:
arr = np.array([1,2,3])

print(arr + 1)
print(arr - 2)
print(arr * 3)
print(arr / 4)
print(arr ** 5)


[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


## Vector math function

In [6]:
arr = np.array([1.01, 2.5, 3.99])

print(np.sqrt(arr))
print(np.ceil(arr))
print(np.pi)

[1.00498756 1.58113883 1.99749844]
[2. 3. 4.]
3.141592653589793


## Element wise arithmetic

The operation will take place between elements at same position

In [ ]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)
print(a1 ** a2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


## Comparision Operator

Using comparsion operators we can create boolean arrays, filter data and use element wise comparsions

In [11]:
scores = np.array([91,55,100,73,82,64])

print(scores == 100)
print(scores >= 60)

[False False  True False False False]
[ True False  True  True  True  True]
