# Numpy Arrays

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray

In [2]:
arr = np.array((1, 2, 3, 4, 5))

print(arr) 

[1 2 3 4 5]


### Dimension in arrays

A dimension in arrays is one level of array depth (nested arrays).

In [4]:
# 0-D Array
a = np.array(42)

print(a)

42


In [5]:
# 1-D Array

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
# 2-D Array
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
# 3-D Array
a = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [10]:
print(a.ndim)

3


## Array Indexing

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [11]:
arr = np.array([1,2,3,4,5])

print(arr[0]) # accessing the 1st element

1


The arrays follow the same indexing as the lists

In [12]:
# access 2-D arrays

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1]) 

2nd element on 1st row:  2


In [13]:
# negative indexing

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1]) 


Last element from 2nd dim:  10


## Array Slicing

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) 

[2 3 4 5]


The result includes the start index, but excludes the end index.

In [15]:
print(arr[4:]) 

[5 6 7]


In [16]:
print(arr[:4]) # Slice elements from the beginning to index 4 (not included):

[1 2 3 4]


In [17]:
# Negative Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1]) 

[5 6]


In [18]:
# Using step value to determine the step of the slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2]) 

[2 4]


In [19]:
# Returning every other element from the entire array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2]) 

[1 3 5 7]


In [21]:
# Slicing 2D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4]) # From the second element, slice elements from index 1 to index 4 (not included):

[7 8 9]


Creating Arrays With a Defined Data Type

using the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [22]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype) 

[b'1' b'2' b'3' b'4']
|S1


In [23]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype) 

[1 2 3 4]
int32


In [24]:
arr = np.array(['a', '2', '3'], dtype='i') 

ValueError: invalid literal for int() with base 10: 'a'

Converting Data Type on Existing Arrays

The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [25]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype) 

[1 2 3]
int32
