In [2]:
import numpy as np

# Broadcasting


Broadcasting allows Numpy to preform operations on arrays with different shapes by virtually expanding dimensions so they match the larger arrays shape

Rules to follow:
- the dimensions have the same size
- or
- One of the dimensions has a size of 1

In [2]:
a1 = np.array([[1,2,3,4]])
a2 = np.array([[1],[2],[3],[4]])

print(a1 * a2)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [3]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a2 = np.array([[1],[2],[3],[4]])

print(a1 * a2)

ValueError: operands could not be broadcast together with shapes (2,4) (4,1) 

# Aggregate Functions

They summarize data and typically return a single value

In [3]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])

print(f"Sum = {np.sum(a)}")
print(f"Mean = {np.mean(a)}")
print(f"Standard Deviation = {np.std(a)}")
print(f"variance = {np.var(a)}")
print(f"Min = {np.min(a)}")
print(f"Max = {np.max(a)}")
print(f"Position of min value = {np.argmin(a)}")
print(f"Position of max value = {np.argmax(a)}")

print(f"Sum of all columns = {np.sum(a, axis=0)}")
print(f"Sum of all rows = {np.sum(a, axis=1)}")



Sum = 55
Mean = 5.5
Standard Deviation = 2.8722813232690143
variance = 8.25
Min = 1
Max = 10
Position of min value = 0
Position of max value = 9
Sum of all columns = [ 7  9 11 13 15]
Sum of all rows = [15 40]
